services:
  mongodb:
    image: mongo:7
    container_name: xionimus_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: xionimus_ai
    networks:
      - xionimus_network

  backend:
    image: xionimus-backend
    container_name: xionimus_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=xionimus_ai
      - CORS_ORIGINS=*
    depends_on:
      - mongodb
    networks:
      - xionimus_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: xionimus-frontend
    container_name: xionimus_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - GENERATE_SOURCEMAP=false
    depends_on:
      - backend
    networks:
      - xionimus_network

volumes:
  mongodb_data:
    driver: local

networks:
  xionimus_network:
    driver: bridge