# Prometheus Configuration for Xionimus AI

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'xionimus-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Xionimus AI Backend
  - job_name: 'xionimus-backend'
    static_configs:
      - targets: ['localhost:8001']
        labels:
          service: 'backend'
          app: 'xionimus-ai'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          service: 'node-exporter'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']