import React, { useState, useEffect } from 'react'
import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
  Button,
  VStack,
  FormControl,
  FormLabel,
  Select,
  Input,
  Textarea,
  HStack,
  Text,
  Alert,
  AlertIcon,
  Spinner,
  Box,
  useToast,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  Switch
} from '@chakra-ui/react'
import { useGitHub } from '../contexts/GitHubContext'

interface GitHubPushDialogProps {
  isOpen: boolean
  onClose: () => void
  generatedCode?: string
}

export const GitHubPushDialog: React.FC<GitHubPushDialogProps> = ({
  isOpen,
  onClose,
  generatedCode = ''
}) => {
  const {
    isConnected,
    user,
    repositories,
    branches,
    selectedRepo,
    selectedBranch,
    connectGitHub,
    fetchRepositories,
    fetchBranches,
    setSelectedRepo,
    setSelectedBranch,
    pushToGitHub,
    createRepository
  } = useGitHub()

  const [isPushing, setIsPushing] = useState(false)
  const [commitMessage, setCommitMessage] = useState('Code generated by Xionimus AI')
  const [fileName, setFileName] = useState('index.tsx')
  const [fileContent, setFileContent] = useState(generatedCode)
  
  // New repository creation
  const [newRepoName, setNewRepoName] = useState('')
  const [newRepoDescription, setNewRepoDescription] = useState('')
  const [newRepoPrivate, setNewRepoPrivate] = useState(false)
  const [isCreatingRepo, setIsCreatingRepo] = useState(false)

  const toast = useToast()

  useEffect(() => {
    if (isConnected && isOpen) {
      fetchRepositories()
    }
  }, [isConnected, isOpen])

  useEffect(() => {
    if (selectedRepo) {
      const [owner, repo] = selectedRepo.split('/')
      fetchBranches(owner, repo)
    }
  }, [selectedRepo])

  useEffect(() => {
    setFileContent(generatedCode)
  }, [generatedCode])

  const handleConnect = async () => {
    try {
      await connectGitHub()
    } catch (error) {
      toast({
        title: 'Fehler',
        description: 'GitHub Verbindung fehlgeschlagen',
        status: 'error',
        duration: 5000
      })
    }
  }

  const handleCreateRepo = async () => {
    if (!newRepoName.trim()) {
      toast({
        title: 'Fehler',
        description: 'Repository-Name ist erforderlich',
        status: 'error',
        duration: 3000
      })
      return
    }

    setIsCreatingRepo(true)
    try {
      const repo = await createRepository(newRepoName, newRepoDescription, newRepoPrivate)
      toast({
        title: 'Repository erstellt!',
        description: `${repo.full_name} wurde erstellt`,
        status: 'success',
        duration: 3000
      })
      setSelectedRepo(repo.full_name)
      setNewRepoName('')
      setNewRepoDescription('')
    } catch (error: any) {
      toast({
        title: 'Fehler beim Erstellen',
        description: error.response?.data?.detail || 'Repository konnte nicht erstellt werden',
        status: 'error',
        duration: 5000
      })
    } finally {
      setIsCreatingRepo(false)
    }
  }

  const handlePush = async () => {
    if (!selectedRepo) {
      toast({
        title: 'Fehler',
        description: 'Bitte wählen Sie ein Repository',
        status: 'error',
        duration: 3000
      })
      return
    }

    if (!fileName.trim() || !fileContent.trim()) {
      toast({
        title: 'Fehler',
        description: 'Dateiname und Inhalt sind erforderlich',
        status: 'error',
        duration: 3000
      })
      return
    }

    setIsPushing(true)
    try {
      const result = await pushToGitHub(
        [{ path: fileName, content: fileContent }],
        commitMessage
      )

      toast({
        title: 'Erfolgreich gepusht!',
        description: `${result.files_pushed} Datei(en) zu ${result.repository} gepusht`,
        status: 'success',
        duration: 5000
      })

      onClose()
    } catch (error: any) {
      toast({
        title: 'Push fehlgeschlagen',
        description: error.response?.data?.detail || 'Fehler beim Pushen',
        status: 'error',
        duration: 5000
      })
    } finally {
      setIsPushing(false)
    }
  }

  if (!isConnected) {
    return (
      <Modal isOpen={isOpen} onClose={onClose} size="md">
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>Mit GitHub verbinden</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <VStack spacing={4} py={4}>
              <Box
                w="60px"
                h="60px"
                bg="gray.800"
                borderRadius="full"
                display="flex"
                alignItems="center"
                justifyContent="center"
              >
                <svg width="40" height="40" fill="white" viewBox="0 0 16 16">
                  <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/>
                </svg>
              </Box>
              <Text fontSize="lg" fontWeight="600">
                GitHub Verbindung erforderlich
              </Text>
              <Text fontSize="sm" color="gray.500" textAlign="center">
                Verbinden Sie sich mit GitHub, um Code zu pushen
              </Text>
              <Button
                colorScheme="gray"
                bg="gray.800"
                color="white"
                w="100%"
                onClick={handleConnect}
                _hover={{ bg: 'gray.700' }}
              >
                Mit GitHub verbinden
              </Button>
            </VStack>
          </ModalBody>
        </ModalContent>
      </Modal>
    )
  }

  return (
    <Modal isOpen={isOpen} onClose={onClose} size="xl">
      <ModalOverlay />
      <ModalContent maxW="600px">
        <ModalHeader>
          <HStack>
            <Text>📤 Zu GitHub pushen</Text>
            {user && (
              <Text fontSize="sm" color="gray.500">
                ({user.login})
              </Text>
            )}
          </HStack>
        </ModalHeader>
        <ModalCloseButton />
        <ModalBody>
          <Tabs>
            <TabList>
              <Tab>Push zu Repository</Tab>
              <Tab>Neues Repository</Tab>
            </TabList>

            <TabPanels>
              <TabPanel>
                <VStack spacing={4} align="stretch">
                  <FormControl isRequired>
                    <FormLabel>Repository</FormLabel>
                    <Select
                      placeholder="Repository auswählen..."
                      value={selectedRepo || ''}
                      onChange={(e) => setSelectedRepo(e.target.value)}
                    >
                      {repositories.map((repo) => (
                        <option key={repo.id} value={repo.full_name}>
                          {repo.full_name} {repo.private && '🔒'}
                        </option>
                      ))}
                    </Select>
                  </FormControl>

                  <FormControl isRequired>
                    <FormLabel>Branch</FormLabel>
                    <Select
                      value={selectedBranch}
                      onChange={(e) => setSelectedBranch(e.target.value)}
                      isDisabled={!selectedRepo}
                    >
                      {branches.map((branch) => (
                        <option key={branch.name} value={branch.name}>
                          {branch.name}
                        </option>
                      ))}
                    </Select>
                  </FormControl>

                  <FormControl isRequired>
                    <FormLabel>Dateiname</FormLabel>
                    <Input
                      value={fileName}
                      onChange={(e) => setFileName(e.target.value)}
                      placeholder="z.B. src/App.tsx"
                    />
                  </FormControl>

                  <FormControl isRequired>
                    <FormLabel>Dateiinhalt</FormLabel>
                    <Textarea
                      value={fileContent}
                      onChange={(e) => setFileContent(e.target.value)}
                      placeholder="Code hier einfügen..."
                      minH="200px"
                      fontFamily="monospace"
                      fontSize="sm"
                    />
                  </FormControl>

                  <FormControl isRequired>
                    <FormLabel>Commit Message</FormLabel>
                    <Input
                      value={commitMessage}
                      onChange={(e) => setCommitMessage(e.target.value)}
                      placeholder="z.B. Initial commit from Xionimus AI"
                    />
                  </FormControl>

                  {!repositories.length && (
                    <Alert status="info">
                      <AlertIcon />
                      Keine Repositories gefunden. Erstellen Sie ein neues!
                    </Alert>
                  )}
                </VStack>
              </TabPanel>

              <TabPanel>
                <VStack spacing={4} align="stretch">
                  <FormControl isRequired>
                    <FormLabel>Repository-Name</FormLabel>
                    <Input
                      value={newRepoName}
                      onChange={(e) => setNewRepoName(e.target.value)}
                      placeholder="mein-projekt"
                    />
                  </FormControl>

                  <FormControl>
                    <FormLabel>Beschreibung</FormLabel>
                    <Textarea
                      value={newRepoDescription}
                      onChange={(e) => setNewRepoDescription(e.target.value)}
                      placeholder="Projekt-Beschreibung..."
                      rows={3}
                    />
                  </FormControl>

                  <FormControl display="flex" alignItems="center">
                    <FormLabel mb="0">Privates Repository</FormLabel>
                    <Switch
                      isChecked={newRepoPrivate}
                      onChange={(e) => setNewRepoPrivate(e.target.checked)}
                    />
                  </FormControl>

                  <Button
                    bg="linear-gradient(135deg, #00d4ff, #0094ff)"
                    color="white"
                    onClick={handleCreateRepo}
                    isLoading={isCreatingRepo}
                    loadingText="Erstelle..."
                    _hover={{
                      bg: "linear-gradient(135deg, #0094ff, #00d4ff)",
                      boxShadow: "0 0 25px rgba(0, 212, 255, 0.6)"
                    }}
                    boxShadow="0 2px 15px rgba(0, 212, 255, 0.4)"
                  >
                    Repository erstellen
                  </Button>

                  <Alert status="info" fontSize="sm">
                    <AlertIcon />
                    Nach dem Erstellen können Sie im ersten Tab pushen
                  </Alert>
                </VStack>
              </TabPanel>
            </TabPanels>
          </Tabs>
        </ModalBody>

        <ModalFooter>
          <HStack spacing={3}>
            <Button variant="ghost" onClick={onClose}>
              Abbrechen
            </Button>
            <Button
              bg="linear-gradient(135deg, #00d4ff, #0094ff)"
              color="white"
              onClick={handlePush}
              isLoading={isPushing}
              loadingText="Pushe..."
              isDisabled={!selectedRepo || !fileName || !fileContent}
              _hover={{
                bg: "linear-gradient(135deg, #0094ff, #00d4ff)",
                boxShadow: "0 0 25px rgba(0, 212, 255, 0.6)"
              }}
              boxShadow="0 2px 15px rgba(0, 212, 255, 0.4)"
            >
              📤 Zu GitHub pushen
            </Button>
          </HStack>
        </ModalFooter>
      </ModalContent>
    </Modal>
  )
}
