name: Health Check

on:
  push:
    branches: [ main, develop, Genesis ]
  pull_request:
    branches: [ main, Genesis ]

jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Repository health check
      run: |
        echo "============================================"
        echo "✅ Xionimus AI - Repository Health Check"
        echo "============================================"
        echo ""
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref }}"
        echo "Actor: ${{ github.actor }}"
        echo ""
        echo "Checking project structure..."
        
        # Backend check
        if [ -d "backend" ]; then
          echo "✅ Backend directory exists"
          if [ -f "backend/main.py" ]; then
            echo "  ✅ main.py found"
          fi
          if [ -f "backend/requirements.txt" ]; then
            echo "  ✅ requirements.txt found"
          fi
        fi
        
        # Frontend check
        if [ -d "frontend" ]; then
          echo "✅ Frontend directory exists"
          if [ -f "frontend/package.json" ]; then
            echo "  ✅ package.json found"
          fi
          if [ -d "frontend/src" ]; then
            echo "  ✅ src directory found"
          fi
        fi
        
        echo ""
        echo "============================================"
        echo "✅ Health Check PASSED"
        echo "============================================"
        echo ""
        echo "Note: This is a minimal health check."
        echo "No dependencies are installed."
        echo "No tests are run."
        echo "This prevents CI/CD email spam."
        echo ""
        echo "All checks completed successfully!"
